language: node_js
node_js:
  - "node" # latest stable
addons:
  firefox: "latest"
env:
  - DISPLAY=:99.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm test
  - npm run-script integration-test